import { ButtonColumn, Buttons, ProfileTarget } from "../lib/types/buttons.ts";

const controlPanelButtonData: ButtonColumn[] = [
  {
    id: "row1",
    buttons: [
      {
        id: "button1",
        type: Buttons.DIRECT_ACTION_BUTTON,
        label: "Full",
        value: 100,
        styles: {
          background: "bg-green-500 active:bg-green-600",
        },
        profileTarget: ProfileTarget.DIMMER,
      },
      {
        id: "button2",
        type: Buttons.DIRECT_ACTION_BUTTON,
        label: "90%",
        value: 90,
        styles: {
          background: "bg-gray-600 active:bg-gray-700",
          font: "text-white",
        },
        profileTarget: ProfileTarget.DIMMER,
      },
      {
        id: "button3",
        type: Buttons.DIRECT_ACTION_BUTTON,
        label: "80%",
        value: 80,
        styles: {
          background: "bg-gray-600 active:bg-gray-700",
          font: "text-white",
        },
        profileTarget: ProfileTarget.DIMMER,
      },
      {
        id: "button4",
        type: Buttons.DIRECT_ACTION_BUTTON,
        label: "75%",
        value: 75,
        styles: {
          background: "bg-gray-600 active:bg-gray-700",
          font: "text-white",
        },
        profileTarget: ProfileTarget.DIMMER,
      },
      {
        id: "button5",
        type: Buttons.DIRECT_ACTION_BUTTON,
        label: "70%",
        value: 70,
        styles: {
          background: "bg-gray-600 active:bg-gray-700",
          font: "text-white",
        },
        profileTarget: ProfileTarget.DIMMER,
      },
      {
        id: "button6",
        type: Buttons.DIRECT_ACTION_BUTTON,
        label: "60%",
        value: 60,
        styles: {
          background: "bg-gray-600 active:bg-gray-700",
          font: "text-white",
        },
        profileTarget: ProfileTarget.DIMMER,
      },
      {
        id: "button7",
        type: Buttons.DIRECT_ACTION_BUTTON,
        label: "50%",
        value: 50,
        styles: {
          background: "bg-gray-600 active:bg-gray-700",
          font: "text-white",
        },
        profileTarget: ProfileTarget.DIMMER,
      },
      {
        id: "button8",
        type: Buttons.DIRECT_ACTION_BUTTON,
        label: "40%",
        value: 40,
        styles: {
          background: "bg-gray-600 active:bg-gray-700",
          font: "text-white",
        },
        profileTarget: ProfileTarget.DIMMER,
      },
      {
        id: "button9",
        type: Buttons.DIRECT_ACTION_BUTTON,
        label: "30%",
        value: 30,
        styles: {
          background: "bg-gray-600 active:bg-gray-700",
          font: "text-white",
        },
        profileTarget: ProfileTarget.DIMMER,
      },
      {
        id: "button10",
        type: Buttons.DIRECT_ACTION_BUTTON,
        label: "25%",
        value: 25,
        styles: {
          background: "bg-gray-600 active:bg-gray-700",
          font: "text-white",
        },
        profileTarget: ProfileTarget.DIMMER,
      },
      {
        id: "button11",
        type: Buttons.DIRECT_ACTION_BUTTON,
        label: "20%",
        value: 20,
        styles: {
          background: "bg-gray-600 active:bg-gray-700",
          font: "text-white",
        },
        profileTarget: ProfileTarget.DIMMER,
      },
      {
        id: "button12",
        type: Buttons.DIRECT_ACTION_BUTTON,
        label: "10%",
        value: 10,
        styles: {
          background: "bg-gray-600 active:bg-gray-700",
          font: "text-white",
        },
        profileTarget: ProfileTarget.DIMMER,
      },
      {
        id: "button13",
        type: Buttons.DIRECT_ACTION_BUTTON,
        label: "0%",
        value: 0,
        styles: {
          background: "bg-red-700 border-red-800 active:bg-red-800",
          font: "text-white",
        },
        profileTarget: ProfileTarget.DIMMER,
      },
      {
        id: "button14",
        type: Buttons.COMMAND_BUTTON,
        label: "@",
        styles: { background: "bg-gray-300 active:bg-gray-400" },
      },
      {
        id: "button15",
        type: Buttons.COMMAND_BUTTON,
        label: "Clear",
        styles: { background: "bg-black", font: "text-white" },
      },
    ],
  },
  {
    id: "row2",
    buttons: [
      {
        id: "button16",
        type: Buttons.COMMAND_BUTTON,
        label: "Update",
        styles: {
          background: "bg-gray-600 active:bg-gray-700 border-white",
          font: "text-white",
        },
      },
      {
        id: "button17",
        type: Buttons.COMMAND_BUTTON,
        label: "Go To Cue",
        styles: { background: "bg-teal-400 active: bg-teal-500" },
      },
      {
        id: "button18",
        type: Buttons.COMMAND_BUTTON,
        label: "Q",
        styles: {
          background: "border-white active:bg-gray-800",
          font: "text-white",
        },
      },
      {
        id: "button19",
        type: Buttons.COMMAND_BUTTON,
        label: "Record",
        styles: {
          background: "bg-red-700 border-red-800 active:bg-red-800",
          font: "text-white",
        },
      },
      {
        id: "button20",
        type: Buttons.COMMAND_BUTTON,
        label: "Parent",
        styles: { background: "bg-gray-300 active:bg-gray-400" },
      },
      {
        id: "button21",
        type: Buttons.COMMAND_BUTTON,
        label: "Cells Only",
        styles: { background: "bg-gray-300 active:bg-gray-400" },
      },
      {
        id: "button22",
        type: Buttons.COMMAND_BUTTON,
        label: "Recall From",
        styles: {
          background: "border-white active:bg-gray-800",
          font: "text-white",
        },
      },
      {
        id: "button23",
        type: Buttons.COMMAND_BUTTON,
        label: "LAST",
        styles: {
          background: "border-white active:bg-purple-950 border-purple-800",
          font: "text-white",
        },
      },
      {
        id: "button24",
        type: Buttons.DIRECT_ACTION_BUTTON,
        label: "+1",
        value: 1,
        styles: {
          background: "bg-gray-400 active:bg-gray-500",
          font: "text-white",
        },
        profileTarget: ProfileTarget.DIMMER,
      },
      {
        id: "button25",
        type: Buttons.DIRECT_ACTION_BUTTON,
        label: "-1",
        value: -1,
        styles: {
          background: "bg-gray-400 active:bg-gray-500",
          font: "text-white",
        },
        profileTarget: ProfileTarget.DIMMER,
      },
      {
        id: "button26",
        type: Buttons.COMMAND_BUTTON,
        label: "+",
        styles: { background: "bg-gray-300 active:bg-gray-400" },
      },
      {
        id: "button27",
        type: Buttons.KEYPAD_BUTTON,
        label: "7",
        styles: { background: "bg-gray-300 active:bg-gray-400" },
      },
      {
        id: "button28",
        type: Buttons.KEYPAD_BUTTON,
        label: "4",
        styles: { background: "bg-gray-300 active:bg-gray-400" },
      },
      {
        id: "button29",
        type: Buttons.KEYPAD_BUTTON,
        label: "1",
        styles: { background: "bg-gray-300 active:bg-gray-400" },
      },
      {
        id: "button30",
        type: Buttons.COMMAND_BUTTON,
        label: "/",
        styles: {
          background: "bg-gray-400 active:bg-gray-500",
          font: "text-white",
        },
      },
    ],
  },
  {
    id: "row3",
    buttons: [
      {
        id: "button31",
        type: Buttons.COMMAND_BUTTON,
        label: "Oh Shit",
        styles: {
          background: "border-red-800 active:bg-red-700",
          font: "text-white",
        },
      },
      {
        id: "button32",
        type: Buttons.COMMAND_BUTTON,
        label: "Blank",
        styles: { background: "bg-gray-800", font: "text-white" },
      },
      {
        id: "button33",
        type: Buttons.COMMAND_BUTTON,
        label: "Blank",
        styles: { background: "bg-gray-800", font: "text-white" },
      },
      {
        id: "button34",
        type: Buttons.COMMAND_BUTTON,
        label: "Group",
        styles: {
          background: "bg-blue-700 active:bg-blue-800",
          font: "text-white",
        },
      },
      {
        id: "button35",
        type: Buttons.COMMAND_BUTTON,
        label: "OFF/ON",
        styles: {
          background: "border-red-800 active:bg-red-700",
          font: "text-white",
        },
      },
      {
        id: "button36",
        type: Buttons.COMMAND_BUTTON,
        label: "Restore",
        styles: {
          background: "border-red-800 active:bg-red-700",
          font: "text-white",
        },
      },
      {
        id: "button37",
        type: Buttons.COMMAND_BUTTON,
        label: "Capture",
        styles: {
          background: "border-blue-800 active:bg-blue-700",
          font: "text-white",
        },
      },
      {
        id: "button38",
        type: Buttons.COMMAND_BUTTON,
        label: "Select Last",
        styles: {
          background: "border-purple-500 active:bg-purple-950",
          font: "text-white",
        },
      },
      {
        id: "button39",
        type: Buttons.COMMAND_BUTTON,
        label: "Sneak",
        styles: { background: "bg-teal-300" },
      },
      {
        id: "button40",
        type: Buttons.COMMAND_BUTTON,
        label: "Time",
        styles: {
          background: "bg-gray-400 active:bg-gray-500",
          font: "text-white",
        },
      },
      {
        id: "button41",
        type: Buttons.COMMAND_BUTTON,
        label: "Thru",
        styles: {
          background: "bg-gray-300 active:bg-gray-400",
        },
      },
      {
        id: "button42",
        type: Buttons.KEYPAD_BUTTON,
        label: "8",
        styles: { background: "bg-gray-300 active:bg-gray-400" },
      },
      {
        id: "button43",
        type: Buttons.KEYPAD_BUTTON,
        label: "5",
        styles: { background: "bg-gray-300 active:bg-gray-400" },
      },
      {
        id: "button44",
        type: Buttons.KEYPAD_BUTTON,
        label: "2",
        styles: { background: "bg-gray-300 active:bg-gray-400" },
      },
      {
        id: "button45",
        type: Buttons.KEYPAD_BUTTON,
        label: "0",
        styles: { background: "bg-gray-300 active:bg-gray-400" },
      },
    ],
  },
  {
    id: "row4",
    buttons: [
      {
        id: "button46",
        type: Buttons.DIRECT_ACTION_BUTTON,
        label: "Xfade Max",
        value: 1,
        styles: { background: "border-orange-500", font: "text-white" },
        profileTarget: ProfileTarget.CROSSFADE,
      },
      {
        id: "button47",
        type: Buttons.DIRECT_ACTION_BUTTON,
        label: "Xfade Min",
        value: 0,
        styles: { background: "border-orange-500", font: "text-white" },
        profileTarget: ProfileTarget.COLOR_TEMP,
      },
      {
        id: "button48",
        type: Buttons.DIRECT_ACTION_BUTTON,
        label: "+ 1/8 G",
        value: 12.5,
        styles: { background: "bg-green-400 active:bg-green-500" },
        profileTarget: ProfileTarget.TINT,
      },
      {
        id: "button49",
        type: Buttons.DIRECT_ACTION_BUTTON,
        label: "Tint Home",
        value: 0,
        styles: { background: "bg-gray-200 active:bg-gray-300" },
        profileTarget: ProfileTarget.TINT,
      },
      {
        id: "button50",
        type: Buttons.DIRECT_ACTION_BUTTON,
        label: "- 1/8 G",
        value: -12.5,
        styles: { background: "bg-fuchsia-400 active:bg-fuchsia-500" },
        profileTarget: ProfileTarget.TINT,
      },
      {
        id: "button51",
        type: Buttons.COMMAND_BUTTON,
        label: "ID",
        styles: {
          background: "bg-gray-600 active:bg-gray-700 border-red-800",
          font: "text-white",
        },
      },
      {
        id: "button52",
        type: Buttons.COMMAND_BUTTON,
        label: "Parameters",
        styles: { background: "border-white", font: "text-white" },
      },
      {
        id: "button53",
        type: Buttons.COMMAND_BUTTON,
        label: "NEXT",
        styles: {
          background: "border-purple-800 active:bg-purple-950 ",
          font: "text-white",
        },
      },
      {
        id: "button54",
        type: Buttons.DIRECT_ACTION_BUTTON,
        label: "+5",
        styles: {
          background: "bg-gray-400 active:bg-gray-500",
          font: "text-white",
        },
        value: 5,
        profileTarget: ProfileTarget.DIMMER,
      },
      {
        id: "button55",
        type: Buttons.DIRECT_ACTION_BUTTON,
        label: "-5",
        value: -5,
        styles: {
          background: "bg-gray-400 active:bg-gray-500",
          font: "text-white",
        },
        profileTarget: ProfileTarget.DIMMER,
      },
      {
        id: "button56",
        type: Buttons.COMMAND_BUTTON,
        label: "-",
        styles: { background: "bg-gray-300 active:bg-gray-400" },
      },
      {
        id: "button57",
        type: Buttons.KEYPAD_BUTTON,
        label: "9",
        styles: { background: "bg-gray-300 active:bg-gray-400" },
      },
      {
        id: "button58",
        type: Buttons.KEYPAD_BUTTON,
        label: "6",
        styles: { background: "bg-gray-300 active:bg-gray-400" },
      },
      {
        id: "button59",
        type: Buttons.KEYPAD_BUTTON,
        label: "3",
        styles: { background: "bg-gray-300 active:bg-gray-400" },
      },
      {
        id: "button60",
        type: Buttons.KEYPAD_BUTTON,
        label: ".",
        styles: {
          background: "bg-gray-400 active:bg-gray-500",
          font: "text-white",
        },
      },
    ],
  },
  {
    id: "row5",
    buttons: [
      {
        id: "button61",
        type: Buttons.DIRECT_ACTION_BUTTON,
        label: "CCT Max",
        value: 10000,
        styles: { background: "bg-gray-200 active:bg-gray-300" },
        profileTarget: ProfileTarget.COLOR_TEMP,
      },
      {
        id: "button62",
        type: Buttons.DIRECT_ACTION_BUTTON,
        label: "6000",
        value: 6000,
        styles: { background: "bg-blue-200 active:bg-blue-300" },
        profileTarget: ProfileTarget.COLOR_TEMP,
      },
      {
        id: "button63",
        type: Buttons.DIRECT_ACTION_BUTTON,
        label: "5600",
        value: 5600,
        styles: { background: "bg-blue-300 active:bg-blue-400" },
        profileTarget: ProfileTarget.COLOR_TEMP,
      },
      {
        id: "button64",
        type: Buttons.DIRECT_ACTION_BUTTON,
        label: "4200",
        value: 4200,
        styles: { background: "bg-yellow-200 active:bg-yellow-300" },
        profileTarget: ProfileTarget.COLOR_TEMP,
      },
      {
        id: "button65",
        type: Buttons.DIRECT_ACTION_BUTTON,
        label: "3800",
        value: 3800,
        styles: { background: "bg-yellow-400 active:bg-yellow-500" },
        profileTarget: ProfileTarget.COLOR_TEMP,
      },
      {
        id: "button66",
        type: Buttons.DIRECT_ACTION_BUTTON,
        label: "3200",
        value: 3200,
        styles: { background: "bg-yellow-500 active:bg-yellow-600" },
        profileTarget: ProfileTarget.COLOR_TEMP,
      },
      {
        id: "button67",
        type: Buttons.DIRECT_ACTION_BUTTON,
        label: "2800",
        value: 2800,
        styles: { background: "bg-orange-400 active:bg-orange-500" },
        profileTarget: ProfileTarget.COLOR_TEMP,
      },
      {
        id: "button68",
        type: Buttons.DIRECT_ACTION_BUTTON,
        label: "2500",
        value: 2500,
        styles: { background: "bg-orange-500 active:bg-orange-600" },
        profileTarget: ProfileTarget.COLOR_TEMP,
      },
      {
        id: "button69",
        type: Buttons.DIRECT_ACTION_BUTTON,
        label: "2200",
        value: 2200,
        styles: { background: "bg-orange-700 active:bg-oarnge-800" },
        profileTarget: ProfileTarget.COLOR_TEMP,
      },
      {
        id: "button70",
        type: Buttons.DIRECT_ACTION_BUTTON,
        label: "2000",
        value: 2000,
        styles: { background: "bg-orange-800 active:bg-orange-900" },
        profileTarget: ProfileTarget.COLOR_TEMP,
      },
      {
        id: "button71",
        type: Buttons.DIRECT_ACTION_BUTTON,
        label: "CCT Min",
        value: 1000,
        styles: { background: "bg-gray-200 active:bg-gray-300" },
        profileTarget: ProfileTarget.COLOR_TEMP,
      },
      {
        id: "button72",
        type: Buttons.DIRECT_ACTION_BUTTON,
        label: "+100CCT",
        value: 100,
        styles: { background: "bg-blue-300 active:bg-blue-400" },
        profileTarget: ProfileTarget.COLOR_TEMP,
      },
      {
        id: "button73",
        type: Buttons.COMMAND_BUTTON,
        label: "Color Temp",
        styles: { background: "active:bg-gray-800", font: "text-white" },
      },
      {
        id: "button74",
        type: Buttons.DIRECT_ACTION_BUTTON,
        label: "-100CTT",
        value: -100,
        styles: { background: "bg-yellow-300 active:bg-yellow-400" },
        profileTarget: ProfileTarget.COLOR_TEMP,
      },
      {
        id: "button75",
        type: Buttons.COMMAND_BUTTON,
        label: "Confirm",
        styles: {
          background: "border-green-700 active:bg-green-800",
          font: "text-white",
        },
      },
    ],
  },
];

export default controlPanelButtonData;
